
## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep
  cookie_banner:
    enable: false

$primary: #202825 !default
$secondary: #666666 !default
$black: #000000 !default
$light: #f8f9fa !default

$body-color: $primary !default


