theme: osuny-hugo-theme-aaa

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep
  cookie_banner:
    enable: false

$primary: #202825 
$secondary: #666666 
$black: #000000 
$light: #f8f9fa

$body-color: $primary


