theme: osuny-hugo-theme-aaa

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep

cdnkey: https://osuny-1b4da.kxcdn.com
cookie_banner:
  enable: true
  blank: true
  page: https://gdpr.eu/cookies/

$main-color: #202825 !default 
$main-background-color: #F3FAF7 !default
$body-color: $main-color !default
